#!/usr/bin/env bash
# Turn the single-process SSR server into a multi-worker cluster.
#
# Why: one Node process uses one CPU core. On a 12-core / 48 GB VPS that wastes
# ~90% of the machine and falls over under concurrent users. This installs a
# systemd template unit (one worker per port) and points nginx at all of them
# with least-connections balancing, so traffic spreads across cores and a
# worker restart never takes the site down.
#
# Usage (as root on the VPS):
#   bash deploy/scale-cluster.sh          # 8 workers (ports 3000..3007)
#   WORKERS=4 bash deploy/scale-cluster.sh
set -euo pipefail

APP_DIR="/var/www/nexuraai"
WORKERS="${WORKERS:-8}"
BASE_PORT="${BASE_PORT:-3000}"

if [ "$WORKERS" -lt 1 ] || [ "$WORKERS" -gt 12 ]; then
  echo "!! WORKERS must be between 1 and 12 (this box has 12 cores)"; exit 1
fi

echo "==> installing templated worker unit"
install -m 644 "$APP_DIR/deploy/nexuraai@.service" /etc/systemd/system/nexuraai@.service
systemctl daemon-reload

# The old single-instance unit would fight for port 3000.
if systemctl is-enabled --quiet nexuraai 2>/dev/null; then
  echo "==> disabling legacy single-process unit"
  systemctl disable --now nexuraai || true
fi

echo "==> generating nginx upstream with $WORKERS workers"
{
  echo "# generated by deploy/scale-cluster.sh — do not edit by hand"
  echo "upstream nexuraai_app {"
  echo "    least_conn;"
  for i in $(seq 0 $((WORKERS - 1))); do
    echo "    server 127.0.0.1:$((BASE_PORT + i)) max_fails=2 fail_timeout=10s;"
  done
  echo "    keepalive 64;"
  echo "}"
} > /etc/nginx/conf.d/nexuraai-upstream.conf

echo "==> starting workers"
for i in $(seq 0 $((WORKERS - 1))); do
  systemctl enable --now "nexuraai@$((BASE_PORT + i)).service"
done

echo "==> reloading nginx"
nginx -t
systemctl reload nginx

sleep 2
for i in $(seq 0 $((WORKERS - 1))); do
  code="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$((BASE_PORT + i))/" || echo 000)"
  echo "worker $((BASE_PORT + i)): $code"
done
curl -sS -o /dev/null -w "public: %{http_code}\n" https://nexuraai.dev || true
